import turtle as tr
import numpy as np
tr.speed(0)
tr.penup()
tr.goto(0,150)
tr.pendown()
def o(n):
	for _ in range(360):
		tr.forward(n)
		tr.right(1)
def l(n):
	for _ in range(180):
		tr.forward(n)
		tr.right(1)
tr.begin_fill()
tr.fillcolor("yellow")
o(4)
tr.end_fill()
tr.penup()
tr.goto(120,30)
tr.pendown()
tr.begin_fill()
tr.fillcolor("blue")
o(0.5)
tr.end_fill()
tr.penup()
tr.goto(-120,30)
tr.pendown()
tr.begin_fill()
o(0.5)
tr.end_fill()
tr.penup()
tr.goto(0,-50)
tr.right(90)
tr.pendown()
tr.width(10)
tr.pencolor("black")
tr.forward(40)
tr.penup()
tr.pencolor("red")
tr.goto(175,-100)
tr.pendown()
l(3)